### ISSUE TITLE
Accept IOS shared URLs

### ISSUE THREAD

**Issue by cdharris** [KasemJaffer/receive_sharing_intent#1]
Thanks for the great work!

Would be super if this plugin also handled sharing of text on android and browser URLs on iOS, e.g. (NSExtensionActivationSupportsWebURLWithMaxCount).

**Comment by KasemJaffer** [comment]
This plugin now supports opening url into the app. Sharing text/url coming up

**Comment by luffynas** [comment]
Thanks @KasemJaffer @cdharris i'am waiting this feature. Sharing text

**Comment by KasemJaffer** [comment]
> Thanks @KasemJaffer @cdharris i'am waiting this feature. Sharing text

Latest version of the library now has this feature
