### ISSUE TITLE
Can't find example app on share activities bottom sheet

### ISSUE THREAD

**Issue by d-silveira** [KasemJaffer/receive_sharing_intent#10]
Hi @KasemJaffer great work, last year I've implemented the Android part of share sending and receiving, but lacking iOS knowledge I couldn't complete my plugin with the iOS part. I've since learn that it is way more complicated than in Android, so Well done, great work.

Despite my praises, I couldn't actually get your example to work, since the receive_sharing_intent app never showed up on my share bottom sheet from the photos app, just like you show on your animated gif.
I'm using Xocde 10.1 and flutter 1.5.4-hotfix.2, on Mac OS X 10.14.2, I did:
1. git clone
2. flutter build ios --no-codesign
3. opened the example in Xcode and ran it in an iPhone XR emulator
4. backgrounded app, opened photos and press share on a photo
5. clicked the activities 3 dots but nothing appeared

Am I missing something?
Thanks,
Regards

**Comment by KasemJaffer** [comment]
Thank you!  I just did the exact same thing in two machines and its working. I am using Version 10.2.1 (10E1001)
