### ISSUE TITLE
Unable to receive .txt file 

### ISSUE THREAD

**Issue by royaldevops** [KasemJaffer/receive_sharing_intent#121]
// For sharing images coming from outside the app while the app is closed
    ReceiveSharingIntent.getInitialMedia().then((List<SharedMediaFile> value) {
      setState(() {
        _sharedFiles = value;
        print("Shared Files----$_sharedFiles");
      });
    });

This method returning null when the user shares the .txt file.

**Comment by Tobivaria** [comment]
I am interested also in using txt files . Since you forked the repo, is it working on your current fork?

**Comment by marcio-ota** [comment]
Still not working..
Images -> getMediaStream : OK
Text lines -> getMediaStream: OK
Text files -> getLinkStream: Erro type 'Null' is not a subtype of type 'String' in type cast

**Comment by royaldevops** [comment]
It is working you can get from branch 121

**Comment by royaldevops** [comment]
You can get it here
https://github.com/royaldevops/receive_sharing_intent/tree/121

**Comment by marcio-ota** [comment]
Will this be applied in this plugin?

**Comment by royaldevops** [comment]
No, still not merged by the kasemJaffer

**Comment by DatabertDuck** [comment]
Hey all!
I would also live having the ability to receive .txt files on iOS!!
Let me know if I can help somehow (Just started with Flutter development though, only experience in python as a scripting language)
