### ISSUE TITLE
iOS: Sharing App will be frozen after sharing intent

### ISSUE THREAD

**Issue by itinance** [KasemJaffer/receive_sharing_intent#131]
Hi. After I was finally able to bring this library to life, I came across a serious issue: the App, that was used to share text into my App, is frozen after this.

Steps to reproduce:

1. Open Safari (it doesn't matter weather it's happening on a real device or in Simulator
2. Select a word or sentence
3. Use "share"
4. Select my App
5. My App will be opened and the selected text will be inserted like in the Example App (which is good so far)
6. Switching back to Safari
7. Safari will be frozen. It feels like a modal dialog would be open, but there is none. Safari needs to be killed and restarted in order to make it work again

Seems that something is missing in the library to operate properly on iOS. Has anyone else faced this issue?

**Comment by case1352** [comment]
i seeing this exact issue as described

**Comment by wonpyoJang** [comment]
I found same issue in youtube app on ios 14.3.

**Comment by ramsmart-inno** [comment]
I am facing an issue which I attached below...

"Unable to install /Users/rammohan/Desktop/github downloads/receive_sharing_intent-master/example/build/ios/iphonesimulator/Runner.app on 71A175DF-2B54-41DB-A675-016BAA20DE64. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Failed to create plugin placeholder for /Users/rammohan/Desktop/github downloads/receive_sharing_intent-master/example/build/ios/iphonesimulator/Runner.app/PlugIns/Sharing Extension.appex
Failed to create promise.
Underlying error (domain=IXErrorDomain, code=2):
	Failed to set placeholder attributes com.kasem.sharing.Sharing-Extension
	Failed to create promise.
  Command: xcrun simctl install 71A175DF-2B54-41DB-A675-016BAA20DE64 /Users/rammohan/Desktop/github downloads/receive_sharing_intent-master/example/build/ios/iphonesimulator/Runner.app
Error launching application on iPhone 8."


Help me to move forward from this issue.

**Comment by ramsmart-inno** [comment]
could someone make a video on - how to integrate receive sharing intent on IOS... It will help more... I am new to IOS

**Comment by qhu91it** [comment]
I stuck at step 5, my app is open but not receive anything, and sharing app also get freeze.

**Comment by goashwin** [comment]
+1 Safari is frozen after sharing

**Comment by orestesgaolin** [comment]
The same happens for other apps that can be shared from

**Comment by KennyChan94P** [comment]
I managed to prevent the Sharing App to be frozen after sharing by doing this workaround? im not sure how to call it but yea, give it a try. 
Make sure the functions in ShareViewController.swift are as below :
```
// comment out the lines that needed to be added in this function
// and add these two lines;
override func viewDidLoad() {
        print("viewDidLoad");
        super.viewDidLoad();
}

// copy paste the whole function to the file
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if let content = extensionContext!.inputItems[0] as? NSExtensionItem {
            if let contents = content.attachments {
                for (index, attachment) in (contents).enumerated() {
                    if attachment.hasItemConformingToTypeIdentifier(imageContentType) {
                        handleImages(content: content, attachment: attachment, index: index)
                    } else if attachment.hasItemConformingToTypeIdentifier(textContentType) {
                        handleText(content: content, attachment: attachment, index: index)
                    } else if attachment.hasItemConformingToTypeIdentifier(fileURLType) {
                        handleFiles(content: content, attachment: attachment, index: index)
                    } else if attachment.hasItemConformingToTypeIdentifier(urlContentType) {
                        handleUrl(content: content, attachment: attachment, index: index)
                    } else if attachment.hasItemConformingToTypeIdentifier(videoContentType) {
                        handleVideos(content: content, attachment: attachment, index: index)
                    }
                }
            }
        }
}
```

what it does is basically launching our Flutter app when the iOS Post Dialog did appear.
the iOS Post Dialog will be dismissed when we go back to the Sharing App.

PS: even if you are sharing the text from the Sharing App to your Flutter in the "More" list

**Comment by KasemJaffer** [comment]
> I managed to prevent the Sharing App to be frozen after sharing by doing this workaround? im not sure how to call it but yea, give it a try.
> Make sure the functions in ShareViewController.swift are as below :
> 
> ```
> // comment out the lines that needed to be added in this function
> // and add these two lines;
> override func viewDidLoad() {
>         print("viewDidLoad");
>         super.viewDidLoad();
> }
> 
> // copy paste the whole function to the file
> override func viewDidAppear(_ animated: Bool) {
>         super.viewDidAppear(animated)
>         if let content = extensionContext!.inputItems[0] as? NSExtensionItem {
>             if let contents = content.attachments {
>                 for (index, attachment) in (contents).enumerated() {
>                     if attachment.hasItemConformingToTypeIdentifier(imageContentType) {
>                         handleImages(content: content, attachment: attachment, index: index)
>                     } else if attachment.hasItemConformingToTypeIdentifier(textContentType) {
>                         handleText(content: content, attachment: attachment, index: index)
>                     } else if attachment.hasItemConformingToTypeIdentifier(fileURLType) {
>                         handleFiles(content: content, attachment: attachment, index: index)
>                     } else if attachment.hasItemConformingToTypeIdentifier(urlContentType) {
>                         handleUrl(content: content, attachment: attachment, index: index)
>                     } else if attachment.hasItemConformingToTypeIdentifier(videoContentType) {
>                         handleVideos(content: content, attachment: attachment, index: index)
>                     }
>                 }
>             }
>         }
> }
> ```
> 
> what it does is basically launching our Flutter app when the iOS Post Dialog did appear.
> the iOS Post Dialog will be dismissed when we go back to the Sharing App.
> 
> PS: it will also work even if you are sharing the text from the Sharing App to your Flutter in the "More" list
