### ISSUE TITLE
[iOS] Received the intent but file does not exist

### ISSUE THREAD

**Issue by beelabcloud** [KasemJaffer/receive_sharing_intent#138]
Everything works fine on Android. Image and video files work well on iOS.
But other files ( .pptx for example) do not work on iOS.
On debug mode, the event is fired and the path received looks ok, but file does not exist in the shared folder.
By the way, I try to print some debug message in the swift code, however none of NSLog, print and os_log works.

**Comment by beelabcloud** [comment]
got it, it has  a prefix "file://" for others file case, 
the other one comes , .txt file cannt be received,

**Comment by LiangLuDev** [comment]
hi , I encountered the same problem, how did you solve it?
tks

**Comment by rsnay** [comment]
In case anyone else runs into this, here's what worked for me (with iOS 15 simulator and Android 8 device):
```dart
        final SharedMediaFile sharedFile = files[0];
        // The path comes through URL-encoded and with file:// prefix on iOS
        final String path = Platform.isIOS
            ? Uri.decodeFull(sharedFile.path).replaceFirst('file://', '')
            : sharedFile.path;
```

**Comment by pro100svitlo** [comment]
I am facing same situation on android with the cold start: 
- `getInitialMedia` contains my file
- but file does not exist within the given `path`

if I share file while app running, all works fine and file exists.

Do you have any idea why?
