### ISSUE TITLE
ios problem: cannot open my app

### ISSUE THREAD

**Issue by llyl** [KasemJaffer/receive_sharing_intent#153]
I am using flutter 2.0.3 and receive_sharing_intent 1.4.5.

For the demo case, I can receive a picture, but JSON file failed.

then, I tried to use it in my own project, the app is shown on the list, but cannot open my app. both picture and JSON file failed. 

I don't know the reason and hope someone can help me. Thanks.

**Comment by LiangLuDev** [comment]
I met the same problem, can you solve it？

**Comment by llyl** [comment]
> @llyl Hey Bro，Have you solved this problem? If so is it convenient to share? Thank you very much!

Yes, I solved it and it's very convenient. But I don't know the reason, I just create a new project and copy everything, and then it works.
