### ISSUE TITLE
Receiving URL of the content

### ISSUE THREAD

**Issue by GCnomore** [KasemJaffer/receive_sharing_intent#154]
Hello,

Is there a way to receive the URL of the content?

For example, when I share a content (image, text, link or video) that is posted on www.testpage.com/products, can I receive www.testpage.com/products?

**Comment by GobindaSaha** [comment]
@GCnomore I had the same issue. Even I could not differenciate the url or text as they are passed through same stream. So what I did is grab (only in case of page url share) the url and passed that to backend to scrap the pages meta tags, images etc. etc. and back to the front end. I don't know about the text share cause it shares only text this case.

**Comment by GCnomore** [comment]
@GobindaSaha I found out that this can't be done right after I posted this question. I am doing exactly what you described, sending only the url and make scraper to grab data from that url.
