### ISSUE TITLE
[iOS] Does not work if the app is already opened

### ISSUE THREAD

**Issue by marchellodev** [KasemJaffer/receive_sharing_intent#172]

**Comment by ThuyenPVT** [comment]
i think you try to use EventBus on this case to solve your problem

**Comment by NikhilMJain** [comment]
Post your `ios/ShareExtension/info.plist` file content

**Comment by marchellodev** [comment]
I had actually re-created the ios folder, did what the readme doc said, and it started working properly. Sorry for not reporting it earlier.

Thanks!
