### ISSUE TITLE
Crash when share image to my app

### ISSUE THREAD

**Issue by aduonggm** [KasemJaffer/receive_sharing_intent#173]
receive_sharing_intent: ^1.4.5
this is Log in firebase crashlytics
has no access to content://media/external/images/media/243
![image](https://user-images.githubusercontent.com/44500153/124342520-c0e71080-dbee-11eb-8579-09b0a9841cc4.png)

**Comment by tneotia** [comment]
We can reproduce this consistently when sharing a .vcf file to our app. @KasemJaffer
