### ISSUE TITLE
ViewController still shows dialog

### ISSUE THREAD

**Issue by edwardhuerta** [KasemJaffer/receive_sharing_intent#18]
I'm opening a new Issue since the one I was posting to is already closed.

The problem is that I open the flutter app with your share plugin in iOS. When the user is finished using the flutter app, he can click on the back arrow on the top left of the screen to go back to the original app he was sharing from, i.e. Safari.

The problem is that after the user goes back, there is still a popup dialog showing the shared message, for example, with the top buttons Cancel and Post. What changes are necessary   to get rid of this?

**Comment by edwardhuerta** [comment]
Btw, a way to test this is to go to Safari, then share the URL.
When the flutter app opens, click on the back arrow on the top left that is something like `<Safari`.

If it doesn't happen the first time, do it a second time or until it happens. Seems to be random imo.

**Comment by EHBradford** [comment]
I have exactly this problem as well. It happens 100% of the time for me.   If I press either button, Cancel or Post, it freezes Safari (or Twitter, or any other program) and I have to kill Safari.

![68756711_2936528066389481_3945007691365089280_n](https://user-images.githubusercontent.com/45748719/63397230-84f68980-c38f-11e9-9089-c721e5e5cbde.jpg)

**Comment by EHBradford** [comment]
I've successfully in my environment managed to void the blocking behavior on text shares and url shares by commenting out some of the following Swift code:

`    private func handleText (content: NSExtensionItem, attachment: NSItemProvider, index: Int) {
        attachment.loadItem(forTypeIdentifier: textContentType, options: nil) { [weak self] data, error in
            
            if error == nil, let item = data as? String, let this = self {
                
                this.sharedText.append(item)
                
                // If this is the last item, save imagesData in userDefaults and redirect to host app
                if index == (content.attachments?.count)! - 1 {
                    let userDefaults = UserDefaults(suiteName: "group.\(this.hostAppBundleIdentifier)")
                    //userDefaults?.set(this.sharedText, forKey: this.sharedKey)
                    //userDefaults?.synchronize()
                    //this.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
                    this.redirectToHostApp(type: .text)
                }
                
            } else {
                self?.dismissWithError()
            }
        }
    }

and 

`    private func handleUrl (content: NSExtensionItem, attachment: NSItemProvider, index: Int) {
        attachment.loadItem(forTypeIdentifier: urlContentType, options: nil) { [weak self] data, error in
            
            if error == nil, let item = data as? URL, let this = self {
                
                this.sharedText.append(item.absoluteString)
                
                // If this is the last item, save imagesData in userDefaults and redirect to host app
                if index == (content.attachments?.count)! - 1 {
                    //let userDefaults = UserDefaults(suiteName: "group.\(this.hostAppBundleIdentifier)")
                    //userDefaults?.set(this.sharedText, forKey: this.sharedKey)
                    //userDefaults?.synchronize()
                    //this.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
                    this.redirectToHostApp(type: .text)
                }
                
            } else {
                self?.dismissWithError()
            }
        }
    }
    
Wish I knew more about working on IOS.

**Comment by KasemJaffer** [comment]
Hi,

Thank you for your feedbacks. I'm aware of this issue. Unfortunately, I haven't found a fix for it yet. If anyone know how to fix this issue please create a pull request, I will review and merge it. Or post your fix here. 

@EHBradford  commenting those lines will break the library 😄

**Comment by MikeCode27** [comment]
Try overriding `viewDidAppear` instead of `viewDidLoad` in ShareViewController.swift. At least in my app, this made the share dialog reliably disappear when redirecting to the Flutter host app. Obviously, there are some important state transitions still going on when viewDidLoad is called.

**Comment by tapkain** [comment]
You must call super.viewDidLoad all the time, dunno if this will fix, but just saying

**Comment by edwardhuerta** [comment]
@MikeCode27 @tapkain 
Can you both create a Pull Request so that we can see exactly your changes?

I also modified my app but I still get the problem that if I share text from Safari, then Safari freezes.

**Comment by DarlyLi** [comment]
@edwardhuerta When I try to move the code in viewDidLoad() to didSelectPost(), the problem is solved

**Comment by KasemJaffer** [comment]
Issue fixed... The fix requires you to update your Sharing Extension Class (please check that in the example project)

**Comment by VictorGa** [comment]
@KasemJaffer I am using the latest Sharing Extension Class, but I do get the dialog. 
I have made all changes as your example but I ran out of ideas of what could be the cause of it.

Do you know what else should I keep in mind?
