### ISSUE TITLE
Intent received not worked for app newly start

### ISSUE THREAD

**Issue by Deepjyoti120** [KasemJaffer/receive_sharing_intent#197]
Hi! I am not able to receive a share link when my app is removed from background.
otherwise intent worked file.
Thank you

**Comment by deep1931** [comment]
Hello, 
Have you found any solution?

**Comment by Deepjyoti120** [comment]
yup

**Comment by Deepjyoti120** [comment]
solved by myself.

**Comment by deep1931** [comment]
Can you please guide me how to do this?

**Comment by Deepjyoti120** [comment]
sure,
you can try this one
https://www.codester.com/items/34312/instagram-profile-reels-downloader-flutter
for me to explain I will guide you next Sunday.
