### ISSUE TITLE
Using your /example project to test your solution. atm not working...

### ISSUE THREAD

**Issue by edwardhuerta** [KasemJaffer/receive_sharing_intent#2]
Hi Kasem,

I am trying to get your /example project working on my computer.

This is what I have done:

1. I cloned your git repo to my computer
2. I am using the code in your /example folder
3. I renamed everything from “com.kasem" to “com.abc" in iOS configuration files
4. I run the project in Xcode
5. It fails 

I get the following error:

Showing All Messages
: -1 : Multiple commands produce '.../receive_sharing_intent/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework':
1) Target 'Runner' has copy command from '.../receive_sharing_intent/example/ios/Flutter/Flutter.framework' to '.../receive_sharing_intent/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”

I tried on a real iPhone and the error is the same.

Could you maybe try the steps 1. to 5. that I wrote down above and see if it works for you when using your /example project?

Thanks!

**Comment by KasemJaffer** [comment]
Please try it on a simulator. This example project won't work on a real device unless you have apple account and register the project.

**Comment by KasemJaffer** [comment]
Example project should work properly on a simulator now
