### ISSUE TITLE
App is not shown in the share sheet iOS

### ISSUE THREAD

**Issue by tapkain** [KasemJaffer/receive_sharing_intent#20]
Hello, I tried the example app. Everything works fine on iOS, however when I try to add the extension to my app, it's not shown in the share sheet. I followed the tutorial, double-checked every config, seems like everything is fine. Maybe somebody encountered the same problem, maybe I've done some silly mistake and trying to fight with the configs? Much appreciate any help

**Comment by tapkain** [comment]
Ok, I found the solution after countless hours staring at the stupid plist file. Just make sure the deployment target for Runner.app and the share extension is the same... in my case the app was for iOS 10 and the share extension was iOS 12.4. Could we include this info to README just in case, to save the lifetime of other people

**Comment by KasemJaffer** [comment]
Thanks! I just included that in the readme.
