### ISSUE TITLE
Share Extension does nothing on iOS

### ISSUE THREAD

**Issue by pixelsnis** [KasemJaffer/receive_sharing_intent#205]
I followed the steps exactly as given on the pub page, and the Share Extension for iOS used to work perfectly before, and now, without changing anything, it no longer works.

Tapping on the app icon in the share sheet makes the screen go darker as if the modal sheet is about to show, and then just fades back away and nothing happens. This issue is persisting on all iOS/iPadOS devices I've tried with. Works as expected on Android, though.

Here's a screen recording of what's happening: https://www.icloud.com/iclouddrive/0c4noRvFmGRz4H7bJwBP9xI-w

Anyone know a fix?

**Comment by pixelsnis** [comment]
Fixed it by following the steps on the README.md on this repo. The pub package is outdated, needs an update.

**Comment by akilanfidelis** [comment]
@pixelsnis  I am facing the same issue, can you tell me what was exactly the problem and how you fixed it.
