### ISSUE TITLE
Everything is working in Android & IOS except audio files from WhatsApp

### ISSUE THREAD

**Issue by Aminadav** [KasemJaffer/receive_sharing_intent#206]
It is very strange. I followed the README documentation and able to receive any files that shared. BUT when I select audio file in WhatsApp and click share it's not working:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '[file:///private/var/mobile/Containers/Shared/AppGroup/444CE7F7-2EB2-47C5-88F8-7368386DA60B/AUDIO-2022-02-10-08-10-51.m4a]()' (OS Error: No such file or directory, errno = 2)
```

Very strange. Images from WhatsApp are working (and they have similar URL like: `/private/var/mobile/Containers/Shared/AppGroup/444CE7F7-2EB2-47C5-88F8-7368386DA60B/PHOTO-2022-02-09-15-21-27.jpg`

**Comment by Aminadav** [comment]
I would like to help fix and debug, but I don't know yet where to start.

```
flutter doctor

[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.0)
[✓] Connected device (3 available)
```

Plugin version: `1.4.5`

**Comment by Aminadav** [comment]
It's very easy to reporudce this issue, try to select and share audio file from whatsapp (like voice message), you will see that there are no permission to read the files bytes by using this intent.

**Comment by Aminadav** [comment]
I was able to fix it using those 2 lines of code:

**Comment by triay0** [comment]
Hello, is this fixed? I would like to include the functionality of sending WhatsApp audio messages in my app. 

Thank you
