### ISSUE TITLE
Single instance of activity in android 

### ISSUE THREAD

**Issue by BenCherif** [KasemJaffer/receive_sharing_intent#215]
when you share a text or image when the app is in background  the app reopened again and create an new instance of the activity , i know that because i set` android:launchMode="singleTop"`  but when i switch to `android:launchMode="singleTask"` one instance is creating but not able to navigate back to previous  screen .Kind regards

**Comment by kizinho** [comment]
have same issues which will lead to memory linkage and it will affect smaller device which leads to app not responding
