### ISSUE TITLE
Not working on IOS - app does receive share

### ISSUE THREAD

**Issue by ascavalcante80** [KasemJaffer/receive_sharing_intent#216]
The app runs perfectly on Android, but on IOS, I had to make several changes to get it deployed and now it's deployed, the app does not appear as an option to receive the shares. Did someone manage to get it running properly on IOS? 
Thanks in advance!

**Comment by irocn** [comment]
ios 15.0 have the same issue.

**Comment by DieGlueckswurst** [comment]
@ascavalcante80  I am also struggling to make it work on iOS. What did you change to actually run the app? Right now XCode throws errors from my `info.plist` of the `Share Extension`. How does your `info.plist` look like?

**Comment by ascavalcante80** [comment]
My `info.plist` is the same one I fork from this project. I'm not familiar with Swift development, so I'm spending some time trying to understand how an IOS app should work without Flutter to receive sharing intents. I'll post here if I make any progress on that.

**Comment by ascavalcante80** [comment]
Ok, actually, I found a similar solution for this implementation [here](https://github.com/JaimilPatel/ReceiveSharing). It worked right out of the box for me. Just to flag; it's a problem with Kasem's project. I could not get this working because I'm really too newbie with Swift programming. Big kudos to Kasem for his work.

**Comment by ascavalcante80** [comment]
I'm closing the issue, as we were very few to face this problem, and we found a workaround.
