### ISSUE TITLE
iOS, flutter.h File not found after following Readme instructions

### ISSUE THREAD

**Issue by mobikats** [KasemJaffer/receive_sharing_intent#220]
Build fails after following all of the Readme instructions for iOS, with:
<img width="914" alt="Screenshot 2022-05-12 at 10 15 39" src="https://user-images.githubusercontent.com/5747434/168024470-c9b05f89-fd6f-4b33-b12a-eaf8bcb774f7.png">

Looking on this [SO post](https://stackoverflow.com/questions/66549471/generatedpluginregistrant-h89-flutter-flutter-h-file-not-found), the "solution" is to delete the ios project folder and recreate it - however, doing that, then adding back in this extension, simply leads back to this position. 

Any guidance on how to resolve this and still keep the share extension would be very welcome, thanks in advance.

**Comment by mobikats** [comment]
Xcode 13.3.1
flutter --version
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (3 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

**Comment by mobikats** [comment]
This was a problem caused by having additional targets created with flutter_flavorizr, I reverted back to the default target and it's ok. I've not actually fixed the flavor targets yet, but I believe they can be.

**Comment by anhtuan23** [comment]
@mobikats Hi, have you managed to make this works with `flutter_flavorizr` yet? I'm having the exactly same problem too. Thanks.

**Comment by anhtuan23** [comment]
Related issues: https://github.com/AngeloAvv/flutter_flavorizr/issues/134 and https://github.com/flutter/flutter/issues/103977

I built successfully following [this advice](https://github.com/AngeloAvv/flutter_flavorizr/issues/134#issuecomment-1311698398) 
> I can build my app after clearing "Objective-C Bridging Header" from Build Settings of target extension.

**Comment by anhtuan23** [comment]
Just for reference, I also have to do this to make this works on all flavors:

For each Target (main app Runner and ShareExtension), go to `Build Settings` > `Packaging` > `Product Bundle Identifier` and set the appropriate bundle identifier based on flavor.

**Comment by anhtuan23** [comment]
Thanks for your reply, I did manage to resolve this problem. Although I ended up using a similar package called `share_handler`.

**Comment by tolotrasamuel** [comment]
If you get 

> [ +660 ms] Failed to build iOS app
> [ +215 ms] Error (Xcode): Undefined symbols:
> 

You should also clear “Other Linker Flags” by removing all flags on TARGETS -> Extension -> Build Settings 
Double click on "Multiple values" >  Select all (Cmd+A)  > Hit minus button > Enter

Do it for the Extension Target only, not the Runner Target.

**Comment by tolotrasamuel** [comment]
> Just for reference, I also have to do this to make this works on all flavors:
> 
> For each Target (main app Runner and ShareExtension), go to `Build Settings` > `Packaging` > `Product Bundle Identifier` and set the appropriate bundle identifier based on flavor.


The Share Extension bundle (Runner.app/PlugIns/Share Extension.appex)  should not be  using the exact same CFBundleIdentifier as the main app (Runner Target) otherwise, it will fail when uploading to the App  Store (it will build to an IPA successfully though).

And it should strictly follow the below formatting.


> Asset validation failed Bad bundle identifier. The bundle identifier 'com.company.app.prod' of the application extension Runner.app/PlugIns/Share Extension.appex should start with the application's bundle identifier 'com.company.app.prod' and not contain more than one period “.” after the application's bundle ID.


Hence these could work

> com.company.app.prod.Share-Extension
> com.company.app.dev.Share-Extension
> com.company.app.preprod.Share-Extension
