### ISSUE TITLE
after sharing, safari is frozen, 

### ISSUE THREAD

**Issue by newengine** [KasemJaffer/receive_sharing_intent#23]

**Comment by newengine** [comment]
move the videwDidLoad code to didSelectPost,  fixed

**Comment by dvlj** [comment]
This is not a good fix, can we share without Post dialog without crash?

**Comment by bestever255** [comment]
Can you provide more information because I have same problem where can I find this code you talked about

**Comment by dvlj** [comment]
try #58

**Comment by bestever255** [comment]
Ok thank you very much last thing that when I try to share a file it says that it fails to prepare to share using iphone 11 in simulator do you know anything about this?

**Comment by dvlj** [comment]
@bestever255 may be the author can help with, show your code and error will be helpful.
