### ISSUE TITLE
receive_sharing_intent: ^1.4.5 unable to build

### ISSUE THREAD

**Issue by plumkodali** [KasemJaffer/receive_sharing_intent#268]
If add   dependencies:
pubspec.yaml
receive_sharing_intent: ^1.4.5

I get this error when I build application in flutter vs code terminal

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':receive_sharing_intent' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31

Is there  any solution for this.

I am using 

Tools • Dart 3.1.1 • DevTools 2.25.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.3 22E252 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.0)
[✓] Connected device (4 available)
[✓] Network resources

 kotlin_version = '1.7.10'

**Comment by Gobinda74** [comment]
This is basically a dead package like react-native-receive-sharing-intent. No maintenance,no upgradation nothing. I've used it two years ago worked fine but now it has so much compatibility issues. You can not downgrade flutter sdk for that but what you can do is - use [flutter_sharing_intent](https://pub.dev/packages/flutter_sharing_intent)

**Comment by plumkodali** [comment]
Thanks for the information will user flutter_sharing_intent

**Comment by KasemJaffer** [comment]
I have recently restarted active maintenance and published a couple releases with fixes, new features and a simplified way of setting up iOS.  I encourage you to check out the latest release [v1.6.4](https://pub.dev/packages/receive_sharing_intent)
