### ISSUE TITLE
No action after trying to share a photo on iOS

### ISSUE THREAD

**Issue by martinogarrizzo5** [KasemJaffer/receive_sharing_intent#273]
After compiling successfully the app, I tried to share a photo from the gallery to the app but then the screen became a little darker like it was launching something and then it turned back normal without sharing effectively the file with my app

**Comment by martinogarrizzo5** [comment]
I investigated more and I found that I didn't setup the app group correctly. Now it works!

**Comment by Lele5353** [comment]
What exactly did you do to solve this problem? The same thing happened to me
