### ISSUE TITLE
When sharing image to app in iOS dialog pops up, how do i remove it?

### ISSUE THREAD

**Issue by emilmakowski** [KasemJaffer/receive_sharing_intent#278]
If we share an image to the app and shouldAutoRedirect method is returning true, you see for 1 second the iOS dialog in the background. How do you hide it or remove it? Looks kind of buggy.

Would be great if you could share files to the app without the dialog popping up.

We have checked the other issues regarding the same problem and none of the solutions mentioned worked to remove the dialog.

Happy for any help or suggestions we can get!

**Comment by KasemJaffer** [comment]
There is no way of avoiding that popup unfortunately. One thing you can do is customize the popup using native iOS code.
