### ISSUE TITLE
Not seeing App as URL target on Android

### ISSUE THREAD

**Issue by bagintz** [KasemJaffer/receive_sharing_intent#3]
I am seeing my app as an intent target for Photos on Android, but not seeing it for URL.  Is there anything specific I need to do there?  I didn't see any changes in the example app since you updated it to allow for URLs?

**Comment by KasemJaffer** [comment]
Sorry, i haven't had the time to update the example project. I will update it in the coming days.

**Comment by KasemJaffer** [comment]
Example project and readme file updated
