### ISSUE TITLE
Deprecated Swift interfaces used

### ISSUE THREAD

**Issue by masewo** [KasemJaffer/receive_sharing_intent#30]
Great plugin, but Xcode did not want to build my project because of deprecated Swift interfaces.

Had to change UIApplicationLaunchOptionsKey to UIApplication.LaunchOptionsKey:

https://github.com/masewo/receive_sharing_intent/commit/3789847201c19cf26867e5fb6075d19bbc5675d0
 
And UIApplicationOpenURLOptionsKey to UIApplication.OpenURLOptionsKey:

https://github.com/masewo/receive_sharing_intent/commit/87682352d2bb6dfa342c2a50e80f10e40d8de990

**Comment by dovy** [comment]
Confirmed this will help it to build. However, the subscriptions don't seem to fire at all. Did you succeed in getting your app to recognize shares being sent to it?

I also have this weird "post" box stuck within the safari browser after share that requires me to quit the app completely. Really frustrating...

**Comment by masewo** [comment]
@dovy Do you have problems with iOS or Android? I only use this plugin for iOS. For Android I implemented intent sharing by my own.
But yes, receiving shares (text) is working for me on both platforms. But I get the weird "post" box in safari too after finishing work in my app and returning back to safari via iOS breadcrumb.

**Comment by dovy** [comment]
I'm having issues on iOS where the recieve stream is not firing. I bet I have some slight config bug going on.

That breadcrumb thing is a real issue. In the emulator it causes the app to basically freeze (safari) until shut down.

**Comment by masewo** [comment]
I had issues too while copy pasting configuration into my existing plists. After picking the example ones everything worked great. Configuration inside Xcode is a pain though.

Yes, safari freezes here too. But it is enough to force close safari to fix. I will check on a real device soon.

**Comment by dovy** [comment]
I am about to check on a real device. Have an IM somewhere we can chat in real-time?  ;)

**Comment by dovy** [comment]
P.S. Inside the Podfile, you need to set ENABLE_BITCODE to `YES`.

`config.build_settings['ENABLE_BITCODE'] = 'YES'`

**Comment by dovy** [comment]
And the breadcrumbs thing in the emulator doesn't exist, so that's good. It must be an emulator bug.

**Comment by neckaros** [comment]
And back on the original subject I have the same issue
@KasemJaffer could you please merge @masewo pull request?

**Comment by neckaros** [comment]
#34

**Comment by KasemJaffer** [comment]
Thank you guys, PR merged and it's included in the latest version 1.3.3
