### ISSUE TITLE
Share any file

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [KasemJaffer/receive_sharing_intent#31]
any posibility of sharing any file into the app? i need it to share a docx - xlsx - pptx

**Comment by boring2** [comment]
@juanjoserodrigolazaro  I also want to open the zip file with my app by sharing to my app. Do you have any idea?

**Comment by hsalazarl** [comment]
this feature would be nice

**Comment by KasemJaffer** [comment]
Version 1.4.0 now supports any type of file
