### ISSUE TITLE
New app is executed each time receiving sharing signal

### ISSUE THREAD

**Issue by ianpark** [KasemJaffer/receive_sharing_intent#35]
On Android device, a new app is launched instead of opening the already launched app each time I share something from the other app to my app (Instagram).

Is it by design or a bug? It does not make sense launching the same app multiple times.

**Comment by wakandan** [comment]
I'm having the same issue. Its trigger the same sharing intent each time and causes duplicating of data.

**Comment by wakandan** [comment]
@ianpark found this post. Hope it helps. https://stackoverflow.com/questions/16693191/prevent-multiple-instances-of-my-android-application-composed-of-a-single-activi/16693417

**Comment by ianpark** [comment]
@wakandan thanks for the link. does it solve your problem? I can't get mine fixed unfortunately.

**Comment by ianpark** [comment]
@wakandan Now I tried again it works. Thanks!

**Comment by wrbl606** [comment]
Hey @ianpark , since the issue is solved, would you mind closing it?

**Comment by KasemJaffer** [comment]
Clothing this issue since it's not related to the plugin.  @wakandan  comment should fix it for you.

**Comment by t-walker-wei** [comment]
> @ianpark found this post. Hope it helps. https://stackoverflow.com/questions/16693191/prevent-multiple-instances-of-my-android-application-composed-of-a-single-activi/16693417

I have changed launchMode to singleInstance / singleTask.After share link from chrome, I still got duplicated executed as the screenshot from recents screen. 
![20200630142021](https://user-images.githubusercontent.com/10123505/86091082-df976080-badd-11ea-8312-17756a55daf7.jpg)

**Comment by nrikiji** [comment]
Same problem.
It seems to reproduce in chrome85.
It doesn't seem to occur in older versions of chrome.

**Comment by nrikiji** [comment]
Causes and Solutions.
only happens in Chrome 83 or above, older versions can't reproduce the issue.

https://stackoverflow.com/questions/63363997/android-my-app-replaces-the-app-which-shared-its-content

**Comment by ycv005** [comment]
>  only happens in Chrome 83 or above, older versions can't reproduce the issue.

This happens also when opening link from whatsapp too.
