### ISSUE TITLE
Dart/Flutter cannot parse content:// URIs natively

### ISSUE THREAD

**Issue by bagintz** [KasemJaffer/receive_sharing_intent#4]
I may be missing something, but while I am successfully getting the Content URI (i.e. content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F41076/LARGE/JPG/1337981437), I am unable to actually retrieve the file in Flutter due to this issue:

https://github.com/flutter/flutter/issues/25659

Does this sound right?

**Comment by KasemJaffer** [comment]
Please use this library to get the absolute path that will work with the dart class **File**

https://pub.dev/packages/flutter_absolute_path

**Comment by KasemJaffer** [comment]
dart/flutter does not support android content uri yet as far as my knowledge

**Comment by bagintz** [comment]
Right, but this library returns, in flutter, the content uri through the message channel.  So we get the image uri, but we can't do anything about it.  Unless I am missing something this makes the plugin unusable for sharing images.  Right?

**Comment by KasemJaffer** [comment]
Unfortunately yes, or at least with this library alone. I forgot to mention this in the documentation. My plan is to make this library return the absolute path instead of a reference uri. In the meantime, please use this library in conjunction with the library i mention above.

**Comment by KasemJaffer** [comment]
I am open to pull requests should anyone is interested.

**Comment by KasemJaffer** [comment]
The api now returns a path that can directly be used with File.dart

**Comment by bagintz** [comment]
Awesome work @KasemJaffer Thank you!!
