### ISSUE TITLE
Cannot share image and video files together 

### ISSUE THREAD

**Issue by bachras** [KasemJaffer/receive_sharing_intent#43]
Hi, 

Thanks for awesome plugin. 

I just tried to share image and video file together, but intent return null and I cannot retrieve file paths on flutter app. Is this an existing issue or am I doing something wrong?

Similar to: https://github.com/KasemJaffer/receive_sharing_intent/issues/25

Thanks

**Comment by KasemJaffer** [comment]
Please use latest version of the plugin
