### ISSUE TITLE
Nothing is copied in iOS

### ISSUE THREAD

**Issue by davizgarzia** [KasemJaffer/receive_sharing_intent#47]
Hi ! 

I'm trying to paste tweet URLs in my app by 'Share this Tweet' button that is available in the Twitter app. 

The thing is that, after a big stress trying to implement the plugin in iOS ... Nothing seems to be copied. The`_sharedText` property always is null and I don't know what is going wrong...

The behavior in iOS
![1](https://user-images.githubusercontent.com/12697648/79587114-52459200-80d2-11ea-80f9-c979483a87b9.gif)

The behavior in Android
![2](https://user-images.githubusercontent.com/12697648/79587131-57a2dc80-80d2-11ea-9528-04b24e62b5ec.gif)

I summon the creator @KasemJaffer, @kr1tzy or @acoutts (I guess that you worked with it because you have an active PR) :) 

Thank you very much !

**Comment by acoutts** [comment]
First thing I'd check is that the URL being passsed in `redirectToHostApp` in `ShareViewController.swift` is using a url you have enabled deep linking for in your `Info.plist`:

```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLName</key>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>com.yourapp</string>
        </array>
    </dict>
</array>
```

<img width="735" alt="Screen Shot 2020-04-17 at 11 54 54 AM" src="https://user-images.githubusercontent.com/9597207/79588677-45a94580-80a2-11ea-8a3f-1106abbc9b20.png">

**Comment by davizgarzia** [comment]
Hi Andrew ! Thank you for your answer :) 

I checked it and it was OK, but with `SharePhotos`URL... I just changed it to `com.twiger` to look it like your code... but doesn't works x_x

	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.twiger</string>
			</array>
		</dict>
	</array>

<img width="561" alt="Captura de pantalla 2020-04-17 a las 18 27 07" src="https://user-images.githubusercontent.com/12697648/79592017-a738d680-80d9-11ea-92b0-6777dfb5443d.png">

**Comment by GRBurst** [comment]
Managed to get it to work a few days ago but hasseled a lot...
What is your group ID in your Main APP, your sharing extension and what did you specify in the Swift view controller?
And what is your bundle id oft your Main APP? Are you switching anything of these values in a dev / prod build?

**Comment by davizgarzia** [comment]
Hi ! @GRBurst and thank you for your answer :) 

Here you have some screenshots of my project with de group ID and the bundle ID of the app and the extension: 

<img width="651" alt="Captura de pantalla 2020-04-19 a las 19 51 43" src="https://user-images.githubusercontent.com/12697648/79695493-72fb1c80-8277-11ea-9df0-cbf68a651656.png">

<img width="681" alt="Captura de pantalla 2020-04-19 a las 19 51 50" src="https://user-images.githubusercontent.com/12697648/79695495-755d7680-8277-11ea-9560-1832d558f15f.png">

<img width="607" alt="Captura de pantalla 2020-04-19 a las 19 52 09" src="https://user-images.githubusercontent.com/12697648/79695498-7a222a80-8277-11ea-9e76-9ef594ac41f0.png">

I didn't modify anything in dev / prod build... Hope that it helps you to see where is my problem.

Thank you again !

**Comment by GRBurst** [comment]
`hostAppBundleIdendifier` is wrong it this case. try it without the share.
`let hostAppBundleIdendifier = "dvzgrz-gmail.com.twiger"`.
tell me if that fixes it already :-)

**Comment by GRBurst** [comment]
also as far as I remember, this lib assumes that your `group id` is the same as the id of your main app, prefixed with `group`. So in your case you have to set it to `group.dvzgrz-gmail.com.twiger` for both, main app and the share extension

**Comment by davizgarzia** [comment]
Wow ! Thank you very much @GRBurst 
I applied your changes and it finally works 🤙

**Comment by GRBurst** [comment]
Nice! Happy to hear that :ok_hand:
