### ISSUE TITLE
iOS receive share fails for files

### ISSUE THREAD

**Issue by aghanti7** [KasemJaffer/receive_sharing_intent#57]
I have followed all the listed steps, and I'm able to get the share extension working in iOS for images and videos.

But with files (PDF/MP3/...) I get the following error in my app once I try to access them (even with a simple File.lengthSync()). Any ideas?

```
2020-05-18 16:16:11.204403+0530 MyApp[46423:2731413] flutter: <MyApp>: received shares (while app in memory): /private/var/mobile/Containers/Shared/AppGroup/4CF07D27-DF44-42B5-A219-27E45B0EF441/Test%20Doc%20Solutions.pdf
2020-05-18 16:16:11.217994+0530 MyApp[46423:2731413] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/private/var/mobile/Containers/Shared/AppGroup/4CF07D27-DF44-42B5-A219-27E45B0EF441/Test%20Doc%20Solutions.pdf' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.lengthSync (dart:io/file_impl.dart:387:5)
#2      checkSharedFilesAndAdd (package:MyApp/util/util.dart:436:29)
#3      _HomeScreenState._handleSharedFiles (package:MyApp/screens/home.dart:75:9)
<asynchronous suspension>
#4      _HomeScreenState.afterFirstLayout.<anonymous closure> (package:MyApp/screens/home.dart:42:15)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#12     ReceiveSharingIntent.getMediaStream.<anonymous closure> (package:receive_sharing_intent/receive_sharing_intent.dart:79:20)
#13     _HandlerEventSink.add (dart:async/stream_transformers.dart:230:18)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#18     CastStreamSubscription._onData (dart:_internal/async_cast.dart:83:11)
#19     _rootRunUnary (dart:async/zone.dart:1192:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#26     _rootRun (dart:async/zone.dart:1180:38)
#27     _CustomZone.run (dart:async/zone.dart:1077:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#30     _rootRun (dart:async/zone.dart:1184:13)
#31     _CustomZone.run (dart:async/zone.dart:1077:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

I am on the latest version of the plugin and Flutter 1.17.1.

**Comment by aghanti7** [comment]
Am I missing any permissions that need to be explicitly added in iOS?

**Comment by aghanti7** [comment]
Note: This is not happening in the bundle that I test from Testflight. It only happens with the production code when testing using a device from Xcode.

**Comment by phamhuusam** [comment]
2020-06-25 10:00:25.038352+0700 Sharing Extension[3579:71904] Failed to inherit CoreMedia permissions from 3576: (null)
2020-06-25 10:00:25.171556+0700 Sharing Extension[3579:71902] [core] SLComposeServiceViewController got NSURL file:///Users/admin/Library/Developer/CoreSimulator/Devices/D205A68A-CB15-431E-B3C6-D41C47C17C8C/data/Media/PhotoData/OutgoingTemp/672D8B37-CD4F-405E-B58C-0D403CB294A3/IMG_0005.JPG for public.jpeg error: (null)
Optional(ShareMedia://dataUrl=ShareKey#media)
2020-06-25 10:00:42.229103+0700 Sharing Extension[3579:71638] [core] SLComposeServiceViewController got attachment coarseType 1

I don't know where config this permissions, can you help me.

**Comment by Dead96** [comment]
After a couple of hours trying to solve the problem, I realized that the path returning from the plugin is URI encoded:
```dart
String path = sharedMediaFile.path;
if(Platform.isIOS) {
     path = Uri.decodeComponent(path.replaceFirst('file://', ''));
}
```
Tested on an ios emulator and it's working!

**Comment by stephanecodes** [comment]
Thank you @Dead96 I was facing this error `FileSystemException: Cannot retrieve length of file,(OS Error: No such file or directory, errno = 2) ` and thought it was an access right but the problem was the same as yours :+1:

**Comment by aghanti7** [comment]
> After a couple of hours trying to solve the problem, I realized that the path returning from the plugin is URI encoded:
> 
> ```dart
> String path = sharedMediaFile.path;
> if(Platform.isIOS) {
>      path = Uri.decodeComponent(path.replaceFirst('file://', ''));
> }
> ```
> 
> Tested on an ios emulator and it's working!

This solved the problem! Awesome @Dead96 thank you!!

**Comment by bestever255** [comment]
> After a couple of hours trying to solve the problem, I realized that the path returning from the plugin is URI encoded:
> 
> ```dart
> String path = sharedMediaFile.path;
> if(Platform.isIOS) {
>      path = Uri.decodeComponent(path.replaceFirst('file://', ''));
> }
> ```
> 
> Tested on an ios emulator and it's working!

Where Should I put this?

**Comment by aghanti7** [comment]
> ```dart
> Uri.decodeComponent
> ```

In the body of:
`_intentDataStreamSubscription = ReceiveSharingIntent.getMediaStream()
        .listen((List<SharedMediaFile> value) async {
      if (value != null) {...}
}`
... and,
`ReceiveSharingIntent.getInitialMedia().then(
        (List<SharedMediaFile> value) async {
      if (value != null) {...}
}`

**Comment by bestever255** [comment]
> > ```dart
> > Uri.decodeComponent
> > ```
> 
> In the body of:
> `_intentDataStreamSubscription = ReceiveSharingIntent.getMediaStream() .listen((List<SharedMediaFile> value) async { if (value != null) {...} }`
> ... and,
> `ReceiveSharingIntent.getInitialMedia().then( (List<SharedMediaFile> value) async { if (value != null) {...} }`

Thank You but it says on iphone failed preparing to share do you have any solution for this?

**Comment by aghanti7** [comment]
> ```dart
> ```dart
> Uri.decodeComponent
> ```
> 
> 
> 
> In the body of:
> _intentDataStreamSubscription = ReceiveSharingIntent.getMediaStream() .listen((List<SharedMediaFile> value) async { if (value != null) {...} }
> ... and,
> ReceiveSharingIntent.getInitialMedia().then( (List<SharedMediaFile> value) async { if (value != null) {...} }
> 
> Thank You but it says on iphone failed preparing to share do you have any solution for this?
> ```

Did you follow all the instructions for creating a share extension on iOS?

**Comment by bestever255** [comment]
> > ```dart
> > ```dart
> > Uri.decodeComponent
> > ```
> > 
> > 
> > In the body of:
> > _intentDataStreamSubscription = ReceiveSharingIntent.getMediaStream() .listen((List value) async { if (value != null) {...} }
> > ... and,
> > ReceiveSharingIntent.getInitialMedia().then( (List value) async { if (value != null) {...} }
> > Thank You but it says on iphone failed preparing to share do you have any solution for this?
> 
> Did you follow all the instructions for creating a share extension on iOS?

Yes but I am not enrolled in the 99$ developer plan does this the cause of the problem?

**Comment by aghanti7** [comment]
> ```dart
> ```dart
> ```dart
> Uri.decodeComponent
> ```
> 
> 
> In the body of:
> _intentDataStreamSubscription = ReceiveSharingIntent.getMediaStream() .listen((List value) async { if (value != null) {...} }
> ... and,
> ReceiveSharingIntent.getInitialMedia().then( (List value) async { if (value != null) {...} }
> Thank You but it says on iphone failed preparing to share do you have any solution for this?
> 
> Did you follow all the instructions for creating a share extension on iOS?
> 
> Yes but I am not enrolled in the 99$ developer plan does this the cause of the problem?
> ```

Not sure about that, sorry!

**Comment by lonelydiver** [comment]
> I have followed all the listed steps, and I'm able to get the share extension working in iOS for images and videos.
> 
> But with files (PDF/MP3/...) I get the following error in my app once I try to access them (even with a simple File.lengthSync()). Any ideas?
> 
> ```
> 2020-05-18 16:16:11.204403+0530 MyApp[46423:[2731413](tel:2731413)] flutter: <MyApp>: received shares (while app in memory): /private/var/mobile/Containers/Shared/AppGroup/4CF07D27-DF44-42B5-A219-27E45B0EF441/Test%20Doc%20Solutions.pdf
> 2020-05-18 16:16:11.217994+0530 MyApp[46423:[2731413](tel:2731413)] [VERBOSE-2:[ui_dart_state.cc](http://ui_dart_state.cc)(157)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/private/var/mobile/Containers/Shared/AppGroup/4CF07D27-DF44-42B5-A219-27E45B0EF441/Test%20Doc%20Solutions.pdf' (OS Error: No such file or directory, errno = 2)
> #0      _File.throwIfError (dart:io/file_impl.dart:645:7)
> #1      _File.lengthSync (dart:io/file_impl.dart:387:5)
> #2      checkSharedFilesAndAdd (package:MyApp/util/util.dart:436:29)
> #3      _HomeScreenState._handleSharedFiles (package:MyApp/screens/home.dart:75:9)
> <asynchronous suspension>
> #4      _HomeScreenState.afterFirstLayout.<anonymous closure> (package:MyApp/screens/home.dart:42:15)
> #5      _rootRunUnary (dart:async/zone.dart:1192:38)
> #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
> #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
> #10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
> #11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
> #12     ReceiveSharingIntent.getMediaStream.<anonymous closure> (package:receive_sharing_intent/receive_sharing_intent.dart:79:20)
> #13     _HandlerEventSink.add (dart:async/stream_transformers.dart:230:18)
> #14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
> #15     _rootRunUnary (dart:async/zone.dart:1192:38)
> #16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
> #18     CastStreamSubscription._onData (dart:_internal/async_cast.dart:83:11)
> #19     _rootRunUnary (dart:async/zone.dart:1192:38)
> #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
> #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> #23     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
> #24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
> #25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
> #26     _rootRun (dart:async/zone.dart:1180:38)
> #27     _CustomZone.run (dart:async/zone.dart:1077:19)
> #28     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
> #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
> #30     _rootRun (dart:async/zone.dart:1184:13)
> #31     _CustomZone.run (dart:async/zone.dart:1077:19)
> #32     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
> #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
> #34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
> #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
> ```
> 
> I am on the latest version of the plugin and Flutter 1.17.1.
