### ISSUE TITLE
Android 5.1.1: Every share opens a new instance

### ISSUE THREAD

**Issue by omidh28** [KasemJaffer/receive_sharing_intent#65]
I followed the example for sharing image intent and it works, But the problem is it doesn't use in-memory app and every time I share image a new instance of app is gonna open and I end up with multiple of the same app in the memory.
Why is that?

**Comment by Aderos** [comment]
Change launch mode singleTop to singleInstance in android manifest https://developer.android.com/guide/components/activities/tasks-and-back-stack
