### ISSUE TITLE
Is there a specific set of mime types supported? 

### ISSUE THREAD

**Issue by maskaravivek** [KasemJaffer/receive_sharing_intent#7]
When I choose an image from my iPhone gallery, sometimes it is not received by the app but it works for some images. Is there just a specific set of mime types supported?

**Comment by ImaginationRoom** [comment]
All images should be supported. Can you try the latest version? It has a fix were sometimes the app was not able to receive images.

**Comment by KasemJaffer** [comment]
All images should be supported. Can you try the latest version? It has a fix were sometimes the app was not able to receive images.

**Comment by maskaravivek** [comment]
It looks like there's an issue on my end. I am getting the file paths correctly but looks like `new File(path)` isn't able to get the actual image file for all image extensions.
