### ISSUE TITLE
App won't launch when receiving a file

### ISSUE THREAD

**Issue by emadal95** [KasemJaffer/receive_sharing_intent#89]
I am able to see the app as a sharing option when I try sharing a JSON file but when I select it, the app never launches and the file is never received. I have the media file receiver set up and if I set a listener to receive text, everything works fine but I am not able to receive any files. I am using an iOS simulator.

**Comment by LiangLuDev** [comment]
@emadal95 Hey Bro，Have you solved this problem? If so is it convenient to share? Thank you very much!
