### ISSUE TITLE
Can't get example app to run

### ISSUE THREAD

**Issue by edwardhuerta** [KasemJaffer/receive_sharing_intent#9]
Hi Kasem,

Thanks for publishing your work. Unfortunately I cannot get it to function and I am hoping you can help out in pointing out what I am doing wrong.

This is what I am doing:
1. I clone your repo
2. I cannot run the example app because your own BundleId is used, so then i rename it
3. I run the example app, and then I start getting errors.

First error : 

`ld: framework not found receive_sharing_intent` (even when the pubspect.yaml points to your library, it still does not work.)

Do you have any ideas on what I can do to get it running? I am wondering how you got it running on your system but I cannot get it running on my own. Perhaps you could try doing what I am doing on a different computer and with a different BundleId to see if you run into any problems yourself.

Thanks in advance.

**Comment by KasemJaffer** [comment]
On your Sharing Extension (NOT your host app)
Remove everything under Linking/Other Linker Flags.

**Comment by KasemJaffer** [comment]
Please follow the following steps to run it successfully
```
$ git clone https://github.com/KasemJaffer/receive_sharing_intent.git
$ cd receive_sharing_intent/example
$ flutter build ios --no-codesign
$ flutter run 
```

**Comment by edwardhuerta** [comment]
@KasemJaffer 
I followed your steps and indeed it is running. Thank you for that.

One final thing that I noticed is that when I share to your app extension, the app opens. So far so good. The thing I would like to change is that when I press on the back button to cancel the share and go back to the original app, the ViewController showing the dialog to share the link is still shown. Would you know how to prevent that from showing and instead just going back to the original app? 

i.e. I do not need two things to be activated (the flutter app AND the ViewController dialog).

Thanks in advance.
