### ISSUE TITLE
Sharing image while app is closed doesn't seem to work on iOS

### ISSUE THREAD

**Issue by Flawe** [KasemJaffer/receive_sharing_intent#96]
Sharing an image while the app is running works fine, but sharing an image while the app is not in memory seems to only work on Android. On iOS nothing happens. Also, with 1.4.1 and Flutter 1.22.0 sharing in the iOS simulator doesn't work at all. I get the 'The was an error while preparing to share' error. Any ideas what could be causing this?

**Comment by Flawe** [comment]
On further investigation, it seems the app does indeed launch through the share extension but crashes immediately. This only happen in debug, however, which I'm fine with for now.

Closing this.

**Comment by bestever255** [comment]
Hello I have the same error can you tell me how I can test it so it does not crash?

**Comment by Abacaxi-Nelson** [comment]
+1 how do you test ?
